# standard jekyll configuration

permalink: date
exclude:  ['Rakefile', 'README.md', 'config.rb']

lsi:      false
auto:     false
safe:     true
pygments: true
markdown: maruku

# configuration required for some pages

domain: blog.example.com
title: GkR's Lair
author: "Ludovic 'GkR' Coues"
email: couesl@gmail.com
